# Generated by Django 5.1.6 on 2025-02-20 10:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_smsverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
