# Generated by Django 5.1.6 on 2025-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_smsverification_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='code',
            field=models.TextField(),
        ),
    ]
