# Generated by Django 5.1.6 on 2025-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(editable=False, unique=True, verbose_name='session key'),
        ),
    ]
